[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "安全动态"
  url = "/security-feed/"
  weight = 15

[[main]]
  name = "BH 议题库"
  url = "/bh-talks/"
  weight = 18

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 30

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10
