colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true

[article]
  showDate = true
  showAuthor = true
  showHero = false
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showPagination = true
  showHeadingAnchors = true
  showViews = true
  showLikes = false
  showComments = true

[list]
  showBreadcrumbs = false
  showSummary = true
  showCards = true
  groupByYear = true
  cardView = true

[comments]
  provider = "giscus"

[giscus]
  repo = "yuhanghuang/yuhanghuang.github.io"
  repoId = "R_kgDORe95LA"
  category = "Announcements"
  categoryId = "DIC_kwDORe95LM4C3u3y"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "zh-CN"

[firebase]
  apiKey = "AIzaSyDSbV0ghT-KujZ-dHcQc51ySuXbIifkrVw"
  authDomain = "yuhang-blog-5387b.firebaseapp.com"
  projectId = "yuhang-blog-5387b"
  storageBucket = "yuhang-blog-5387b.firebasestorage.app"
  messagingSenderId = "737893965012"
  appId = "1:737893965012:web:f15f23ddad98264b636f41"
