# Basic
title: 静水流深
subtitle: 思想的巨人，行动的矮子，还是一个小菜鸡
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">My Github</a>
description: 希望坚持下去 最大的感恩就是不辜负!

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
        #    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: Another Button, description: A button, url: 'http://hyhzz.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 完颜修正
    github: yuhanghuang
    twitter: yuhanghuang6
   #gplus:
    mail: 411523hyh@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
